version: '3.8'

services:
  postgres-maximum-concept:
    image: bitnami/postgresql:latest
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_DB=maximum_concept
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - 'maximum_concept_pg_data:/bitnami/postgresql'

volumes:
  maximum_concept_pg_data: